export const rootUrl = "http://localhost:8000/";
export const symptoms = [
  "abdominal_pain",
  "abnormal_menstruation",
  "acute_liver_failure",
  "altered_sensorium",
  "back_pain",
  "belly_pain",
  "blackheads",
  "bladder_discomfort",
  "blister",
  "blood_in_sputum",
  "bloody_stool",
  "blurred_and_distorted_vision",
  "brittle_nails",
  "bruising",
  "chest_pain",
  "coma",
  "congestion",
  "constipation",
  "continuous_feel_of_urine",
  "cramps",
  "depression",
  "diarrhoea",
  "dischromic _patches",
  "distention_of_abdomen",
  "dizziness",
  "drying_and_tingling_lips",
  "enlarged_thyroid",
  "excessive_hunger",
  "extra_marital_contacts",
  "family_history",
  "fast_heart_rate",
  "fluid_overload",
  "foul_smell_of urine",
  "hip_joint_pain",
  "history_of_alcohol_consumption",
  "increased_appetite",
  "inflammatory_nails",
  "internal_itching",
  "irritability",
  "irritation_in_anus",
  "knee_pain",
  "lack_of_concentration",
  "loss_of_balance",
  "loss_of_smell",
  "malaise",
  "mild_fever",
  "movement_stiffness",
  "mucoid_sputum",
  "muscle_pain",
  "muscle_weakness",
  "neck_pain",
  "obesity",
  "pain_during_bowel_movements",
  "pain_in_anal_region",
  "painful_walking",
  "palpitations",
  "passage_of_gases",
  "phlegm",
  "polyuria",
  "prominent_veins_on_calf",
  "puffy_face_and_eyes",
  "pus_filled_pimples",
  "receiving_blood_transfusion",
  "receiving_unsterile_injections",
  "red_sore_around_nose",
  "red_spots_over_body",
  "redness_of_eyes",
  "runny_nose",
  "rusty_sputum",
  "scurring",
  "silver_like_dusting",
  "sinus_pressure",
  "skin_peeling",
  "slurred_speech",
  "small_dents_in_nails",
  "spinning_movements",
  "stiff_neck",
  "stomach_bleeding",
  "swelled_lymph_nodes",
  "swelling_joints",
  "swelling_of_stomach",
  "swollen_blood_vessels",
  "swollen_extremeties",
  "swollen_legs",
  "throat_irritation",
  "toxic_look_(typhos)",
  "unsteadiness",
  "visual_disturbances",
  "watering_from_eyes",
  "weakness_in_limbs",
  "weakness_of_one_body_side",
  "yellow_crust_ooze",
  "yellow_urine",
  "yellowing_of_eyes"
];

export const disease = [
  "Fungal infection",
  "Allergy",
  "GERD",
  "Chronic cholestasis",
  "Drug Reaction",
  "Peptic ulcer diseae",
  "AIDS",
  "Diabetes",
  "Gastroenteritis",
  "Bronchial Asthma",
  "Hypertension",
  " Migraine",
  "Cervical spondylosis",
  "Paralysis (brain hemorrhage)",
  "Jaundice",
  "Malaria",
  "Chicken pox",
  "Dengue",
  "Typhoid",
  "hepatitis A",
  "Hepatitis B",
  "Hepatitis C",
  "Hepatitis D",
  "Hepatitis E",
  "Alcoholic hepatitis",
  "Tuberculosis",
  "Common Cold",
  "Pneumonia",
  "Dimorphic hemmorhoids(piles)",
  "Heartattack",
  "Varicoseveins",
  "Hypothyroidism",
  "Hyperthyroidism",
  "Hypoglycemia",
  "Osteoarthristis",
  "Arthritis",
  "(vertigo) Paroymsal  Positional Vertigo",
  "Acne",
  "Urinary tract infection",
  "Psoriasis",
  "Impetigo"
];
